
export const initialData = {
    firstName: "",
    secondName: "",
    firstSurname: "",
    secondSurname: "",
    documentType: "",
    documentNumber: "",
    documentPdf: "",
    email: "",
    phone1: "",
    phone2: "",
    nacionality: "",
    currentCountry: "",
    migrant: "",
    livesInColombia: "",
    residencyDepartment: "",
    municipalityOfResidency: "",
    locationInBogota: "",
    address: "",
    stratum: "",
    dateOfBirth: "",
    age: "",
    birthdayOnFormation: "",
    sex: "",
    maritalStatus: "",
    academicLevel: "",
    degreeTitle: "",
    occupation: "",
    formaltOccupation: "",
    contractWorker: "",
    victimArmedConflict: "",
    computer: "",
    logProgramate: "",
    pcAccess: "",
    soloLearnProfile: "",
    dreams: "",
    motivation: "",
    user_id: "",
    variable: ""
};




