export const initialData = {
    firstName: "Jairo",
    secondName: "valentin",
    firstSurname: "solarte",
    secondSurname: "rodriuez",
    documentType: "CC",
    documentNumber: "12345",
    documentPdf: "./document.pdf",
    email: "",
    phone1: "123",
    phone2: "456",
    nacionality: "Colombia",
    currentCountry: "Colombia",
    residencyDepartment: "Bogota",
    municipalityOfResidency: "Bogota",
    locationInBogota: "Kennedy",
    address: "1234",
    stratum: "2",
    dateOfBirth: "2022-12-12",
    age: "23",
    sex: "masculino",
    maritalStatus: "",
    academicLevel: "",
    degreeTitle: "",
    currentOccupation: "",
    contractWorker: "",
    pcAccess: "",
    soloLearnProfile: "",
    areaType: "",
    billPdf:"",
    disability: [],
    familyIncome: 0,
    householdMembers: "",
    numberOfChildren: "",
    internetCompany: "",
    mbCount: 0,
    internetAccess: "no",
    vulnerablePopulation: [],
    studiesPdf: "",
    cvPdf: "",
    unemployementTime: "",
    currentOccupation: "",
    householder: false,
    firstLanguage: "",
    secondLanguage: "",
    languageLevel:"",

};





